In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
import scipy as sp
from matplotlib import pylab, pyplot
%matplotlib inline
pylab.plt.style.use("seaborn-colorblind")

> Numpy Array

> Pandas Series(Numpy Array)

__Difference between numpy and python array__
* Numpy Array holds homogeneous elements
* Bunch of convenient functions

In [3]:
a = np.arange(1, 5)

In [4]:
type (a)

numpy.ndarray

In [5]:
print a.max(), a.argmax(), a.std(), a.var(), a.mean()

4 3 1.11803398875 1.25 2.5


In [6]:
a = np.array([2, 3, 4, 5, 6])
a.dtype

dtype('int64')

In [7]:
a = np.array([1, "SWE"])
a.dtype

dtype('S21')

In [8]:
np.array([1, 2]) + np.array([2, 3])

array([3, 5])

In [9]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
type(3 * np.array([2, 3, 6]))

numpy.ndarray

In [11]:
# &, | ~

In [12]:
np.array([np.array([1, 2]), np.array([4, 5])])

array([[1, 2],
       [4, 5]])

In [13]:
a = np.array([1, 2, 3, 4, 5])
b = a > 3
c = a[b]
c[0] = 10
print a, c

[1 2 3 4 5] [10  5]


In [14]:
# += operator is inplace but + is not

In [15]:
x = np.array([1, 2, 3, 4])
s = x[:3]
s[0] = 100
print x

[100   2   3   4]


In [16]:
# Pandas series: describe
x = pd.Series([2, 3, 4, 5, 3, 4, 5, 100])
x.describe()

count      8.000000
mean      15.750000
std       34.057724
min        2.000000
25%        3.000000
50%        4.000000
75%        5.000000
max      100.000000
dtype: float64

In [17]:
# pandas series have something called index
d = pd.Series([2, 3, 4, 5], index=["A,", "B", "C", "D"])

In [18]:
print d[1], d['B'], d.loc['B'], d.iloc[1]
d.argmax()

3 3 3 3


'D'

In [19]:
d['B'] = 4

In [20]:
d.loc['C'] = 1

In [21]:
d

A,    2
B     4
C     1
D     5
dtype: int64

In [22]:
s1 = pd.Series(data=[1, 2, 3, 4], index=list("abcd"))
s2 = pd.Series(data=[10, 20, 30, 40], index=list("abcd"))
s1 + s2

a    11
b    22
c    33
d    44
dtype: int64

In [23]:
# Behaviour of two series with arithmatic operations
s1 = pd.Series(data=[1, 2, 3, 4], index=list("abcd"))
s2 = pd.Series(data=[10, 20, 30, 40], index=list("bdac"))
s1 + s2

a    31
b    12
c    43
d    24
dtype: int64

In [24]:
s1 = pd.Series(data=[1, 2, 3, 4], index=list("abcd"))
s2 = pd.Series(data=[10, 20, 30, 40], index=list("abef"))
s1 + s2

a    11.0
b    22.0
c     NaN
d     NaN
e     NaN
f     NaN
dtype: float64

In [25]:
s1 = pd.Series(data=[1, 2, 3, 4], index=list("abcd"))
s2 = pd.Series(data=[10, 20, 30, 40], index=list("efgh"))
s1 + s2

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

In [26]:
s1.add(s2, fill_value=0)

a     1.0
b     2.0
c     3.0
d     4.0
e    10.0
f    20.0
g    30.0
h    40.0
dtype: float64